[package]
name = "ru_annoy"
version = "0.1.0"
authors = ["ng8eke"]
license = "MIT"
repository = "https://github.com/ng8eke/fareast"
description = """
A rust implementation of annoy(https://github.com/spotify/annoy) (Index serving only). Providing C api as well
"""

[dependencies]
libc = "0.2"
memmap = "0.6"


[lib]
crate-type = ["lib", "cdylib"]
